debug: false

logging:
  level:
    arile.toy.stock_service: debug
    org.spring.framework.web.servlet: debug

spring:
  application.name: stock-service
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PW}
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true

#  spring:
#    redis:
#      url: ${REDIS_URL}

  sql.init.mode: always

  security.oauth2.client:
    registration:
      github:
        client-id: ${GITHUB_OAUTH_CLIENT_ID}
        client-secret: ${GITHUB_OAUTH_CLIENT_SECRET}


---

spring:
  config.activate.on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username:
    password:


---

spring:
  config.activate.on-profile: heroku
  datasource:
    url: ${JAWSDB_URL}
  jpa:
    hibernate.ddl-auto: create
    defer-datasource-initialization: true
  sql.init.mode: always