debug: false

logging:
  level:
    arile.toy.stockservice: debug
    org.spring.framework.web.servlet: debug

spring:
  application.name: stock-service
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
  sql.init.mode: always
